/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type IdentificationResponseModel struct {
	Type_          string `json:"type,omitempty"`
	Value          string `json:"value,omitempty"`
	ExpirationDate string `json:"expiration_date,omitempty"`
}
