/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type CardSwapHash struct {
	PreviousCardToken string `json:"previous_card_token"`
	NewCardToken      string `json:"new_card_token"`
}
