/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type WebhookUpdateCustomHeaderRequest struct {
	// Custom headers to be passed along with request
	CustomHeader map[string]string `json:"custom_header,omitempty"`
}
