/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type ControlTokenRequest struct {
	// Token associated with the card
	CardToken string `json:"card_token"`
	// Type of control token required
	ControltokenType string `json:"controltoken_type,omitempty"`
}
