/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type InternalFindOriginalResponse struct {
	OriginalFound      bool                              `json:"originalFound,omitempty"`
	OriginalTranlog    *InternalAuthorizationTransaction `json:"original_tranlog,omitempty"`
	FundingTransaction *FundingTranlog                   `json:"funding_transaction,omitempty"`
	FinderName         string                            `json:"finder_name,omitempty"`
	Context            map[string]string                 `json:"context,omitempty"`
	Response           *Response                         `json:"response,omitempty"`
}
