/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type CardProductConfig struct {
	Poi                       *Poi                       `json:"poi,omitempty"`
	TransactionControls       *TransactionControls       `json:"transaction_controls,omitempty"`
	SelectiveAuth             *SelectiveAuth             `json:"selective_auth,omitempty"`
	Special                   *Special                   `json:"special,omitempty"`
	CardLifeCycle             *CardLifeCycle             `json:"card_life_cycle,omitempty"`
	ClearingAndSettlement     *ClearingAndSettlement     `json:"clearing_and_settlement,omitempty"`
	JitFunding                *JitFunding                `json:"jit_funding,omitempty"`
	DigitalWalletTokenization *DigitalWalletTokenization `json:"digital_wallet_tokenization,omitempty"`
	Fulfillment               *CardProductFulfillment    `json:"fulfillment,omitempty"`
}
