/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ClientAccessTokenRequest struct {
	ApplicationToken string `json:"application_token,omitempty"`
	CardToken string `json:"card_token"`
}
