/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type PushToCardRequest struct {
	Address1   string `json:"address_1"`
	Address2   string `json:"address_2,omitempty"`
	City       string `json:"city"`
	State      string `json:"state"`
	Zip        string `json:"zip"`
	Country    string `json:"country"`
	Token      string `json:"token,omitempty"`
	UserToken  string `json:"user_token"`
	NameOnCard string `json:"name_on_card,omitempty"`
	Pan        string `json:"pan"`
	Cvv        string `json:"cvv"`
	ExpDate    string `json:"exp_date"`
}
