/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

import (
	"time"
)

type DirectDepositAccountResponse struct {
	AccountNumber        string `json:"account_number"`
	RoutingNumber        string `json:"routing_number"`
	Token                string `json:"token"`
	UserToken            string `json:"user_token"`
	BusinessToken        string `json:"business_token"`
	State                string `json:"state"`
	AllowImmediateCredit bool   `json:"allow_immediate_credit"`
	Type_                string `json:"type,omitempty"`
	// yyyy-MM-ddTHH:mm:ssZ
	CreatedTime *time.Time `json:"created_time"`
	// yyyy-MM-ddTHH:mm:ssZ
	LastModifiedTime *time.Time `json:"last_modified_time"`
}
