/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type Available struct {
	// Uses available
	Uses   int32   `json:"uses"`
	Amount float32 `json:"amount"`
	// Days remaining
	DaysRemaining int32 `json:"days_remaining,omitempty"`
}
