/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type IssuerFraudView struct {
	Score             int32    `json:"score,omitempty"`
	RiskLevel         string   `json:"risk_level,omitempty"`
	RuleViolations    []string `json:"rule_violations,omitempty"`
	RecommendedAction string   `json:"recommended_action,omitempty"`
}
