/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type BulkIssuanceRequest struct {
	Token                   string            `json:"token"`
	Fulfillment             *Fulfillment      `json:"fulfillment"`
	Expedite                bool              `json:"expedite,omitempty"`
	CardProductToken        string            `json:"card_product_token"`
	CardAllocation          int32             `json:"card_allocation"`
	UserAssociation         *UserAssociation  `json:"user_association,omitempty"`
	NameLine1NumericPostfix bool              `json:"name_line_1_numeric_postfix,omitempty"`
	NameLine1RandomPostfix  bool              `json:"name_line_1_random_postfix,omitempty"`
	ExpirationOffset        *ExpirationOffset `json:"expiration_offset,omitempty"`
}
