/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type InternalNetworkTransactionRequest struct {
	Token string `json:"token"`
	// Encryption key ID
	EncryptionKeyId string `json:"encryption_key_id,omitempty"`
	Message         string `json:"message"`
	Network         string `json:"network"`
	Debit           bool   `json:"debit"`
}
