/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

import (
	"time"
)

type InternalDigitalWallet struct {
	Id                        int64                  `json:"id,omitempty"`
	Token                     string                 `json:"token,omitempty"`
	Card                      *InternalCard          `json:"card,omitempty"`
	State                     string                 `json:"state,omitempty"`
	StateReason               string                 `json:"state_reason,omitempty"`
	FulfillmentStatus         string                 `json:"fulfillment_status,omitempty"`
	IssuerEligibilityDecision string                 `json:"issuer_eligibility_decision,omitempty"`
	CreatedTime               *time.Time             `json:"created_time,omitempty"`
	LastModifiedTime          *time.Time             `json:"last_modified_time,omitempty"`
	TokenServiceProvider      *TokenServiceProvider  `json:"token_service_provider,omitempty"`
	Device                    *Device                `json:"device,omitempty"`
	WalletProviderProfile     *WalletProviderProfile `json:"wallet_provider_profile,omitempty"`
	AddressVerification       *AddressVerification   `json:"address_verification,omitempty"`
	Response                  *Response              `json:"response,omitempty"`
}
