/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type MonitorResponse struct {
	Success  bool                   `json:"success,omitempty"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	Errors   []string               `json:"errors,omitempty"`
}
