/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type TransactionOptions struct {
	AdditionalData                     string `json:"additional_data,omitempty"`
	DatabaseTransactionTimeout         int32  `json:"database_transaction_timeout,omitempty"`
	TransactionTimeoutThresholdSeconds int64  `json:"transaction_timeout_threshold_seconds,omitempty"`
	PreAuthTimeLimit                   string `json:"pre_auth_time_limit,omitempty"`
	SendExpirationDate                 bool   `json:"send_expiration_date,omitempty"`
	SendTrackData                      bool   `json:"send_track_data,omitempty"`
	CardExpirationDateYymm             string `json:"card_expiration_date_yymm,omitempty"`
	EncryptionKeyId                    string `json:"encryption_key_id,omitempty"`
	TransactionToken                   string `json:"transaction_token,omitempty"`
	IsAsync                            bool   `json:"is_async,omitempty"`
}
