/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type Device struct {
	Token        string `json:"token,omitempty"`
	Type_        string `json:"type,omitempty"`
	LanguageCode string `json:"language_code,omitempty"`
	DeviceId     string `json:"device_id,omitempty"`
	PhoneNumber  string `json:"phone_number,omitempty"`
	Name         string `json:"name,omitempty"`
	Location     string `json:"location,omitempty"`
	IpAddress    string `json:"ip_address,omitempty"`
}
