/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type CardholderAuthenticationData struct {
	ElectronicCommerceIndicator string `json:"electronic_commerce_indicator,omitempty"`
	VerificationResult          string `json:"verification_result,omitempty"`
	VerificationValueCreatedBy  string `json:"verification_value_created_by,omitempty"`
	ThreeDsMessageVersion       string `json:"three_ds_message_version,omitempty"`
	AuthenticationMethod        string `json:"authentication_method,omitempty"`
	AuthenticationStatus        string `json:"authentication_status,omitempty"`
}
