/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type GatewayProgramFundingSourceUpdateRequest struct {
	Name string `json:"name,omitempty"`
	// Empty string (disabled); must be HTTPS
	Url    string `json:"url"`
	Active bool   `json:"active,omitempty"`
	// Required if URL is present
	BasicAuthUsername string `json:"basic_auth_username"`
	// Required if URL is present; must contain upper and lowercase letters, numbers, and symbols
	BasicAuthPassword string `json:"basic_auth_password"`
	// Total timeout in milliseconds for gateway processing
	TimeoutMillis int64 `json:"timeout_millis,omitempty"`
	// Custom headers
	CustomHeader map[string]string `json:"custom_header,omitempty"`
	// Use MTLS for funding request
	UseMtls bool `json:"use_mtls,omitempty"`
}
