/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

import (
	"time"
)

type MsaOrderRequest struct {
	Token         string `json:"token,omitempty"`
	CampaignToken string `json:"campaign_token"`
	// Required if 'business_token' is null
	UserToken string `json:"user_token,omitempty"`
	// Required if 'user_token' is null
	BusinessToken  string  `json:"business_token,omitempty"`
	CurrencyCode   string  `json:"currency_code"`
	PurchaseAmount float32 `json:"purchase_amount"`
	// default is 0.00
	RewardAmount float32 `json:"reward_amount,omitempty"`
	// default is 0.01
	RewardTriggerAmount       float32    `json:"reward_trigger_amount,omitempty"`
	StartDate                 *time.Time `json:"start_date,omitempty"`
	EndDate                   *time.Time `json:"end_date,omitempty"`
	FundingSourceToken        string     `json:"funding_source_token"`
	FundingSourceAddressToken string     `json:"funding_source_address_token,omitempty"`
}
