/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type TokenRequest struct {
	Token string `json:"token,omitempty"`
	// required if 'business_token' is null
	UserToken string `json:"user_token,omitempty"`
	// required if 'user_token' is null
	BusinessToken    string `json:"business_token,omitempty"`
	AccountNumber    string `json:"account_number"`
	CvvNumber        string `json:"cvv_number"`
	ExpDate          string `json:"exp_date"`
	Zip              string `json:"zip,omitempty"`
	PostalCode       string `json:"postal_code,omitempty"`
	IsDefaultAccount bool   `json:"is_default_account,omitempty"`
}
