/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type OriginalDataElements struct {
	Mti  string `json:"mti,omitempty"`
	Stan string `json:"stan,omitempty"`
	// yyyyMMddHHmmss
	TransmissionTime        string `json:"transmission_time,omitempty"`
	AcquiringInstitutionId  string `json:"acquiring_institution_id,omitempty"`
	NetworkReferenceId      string `json:"network_reference_id,omitempty"`
	ForwardingInstitutionId string `json:"forwarding_institution_id,omitempty"`
	TransactionToken        string `json:"transaction_token,omitempty"`
}
