/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

import (
	"time"
)

type DirectDepositAccountTransitionResponse struct {
	Token         string `json:"token"`
	UserToken     string `json:"user_token"`
	BusinessToken string `json:"business_token"`
	AccountToken  string `json:"account_token"`
	State         string `json:"state"`
	Channel       string `json:"channel"`
	Reason        string `json:"reason"`
	// yyyy-MM-ddTHH:mm:ssZ
	CreatedTime *time.Time `json:"created_time"`
}
