/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type CreateCacheRequestEntry struct {
	Token       string `json:"token,omitempty"`
	SendWebhook bool   `json:"send_webhook,omitempty"`
	SendTms     bool   `json:"send_tms,omitempty"`
	ForceUpdate bool   `json:"force_update,omitempty"`
}
