/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type Transaction struct {
	International bool `json:"international,omitempty"`
	// address verification
	AddressVerification *InternalAddressVerificationRequest `json:"address_verification,omitempty"`
	IsInternational     bool                                `json:"is_international,omitempty"`
	Network             string                              `json:"network"`
	Currency            string                              `json:"currency,omitempty"`
}
