/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

import (
	"time"
)

type PushToCardResponse struct {
	// yyyy-MM-ddTHH:mm:ssZ
	CreatedTime *time.Time `json:"created_time"`
	// yyyy-MM-ddTHH:mm:ssZ
	LastModifiedTime             *time.Time `json:"last_modified_time"`
	Address1                     string     `json:"address_1,omitempty"`
	Address2                     string     `json:"address_2,omitempty"`
	City                         string     `json:"city,omitempty"`
	State                        string     `json:"state,omitempty"`
	Zip                          string     `json:"zip,omitempty"`
	Country                      string     `json:"country,omitempty"`
	LastFour                     string     `json:"last_four,omitempty"`
	Token                        string     `json:"token,omitempty"`
	FastFundTransferEligible     bool       `json:"fast_fund_transfer_eligible,omitempty"`
	GamblingFundTransferEligible bool       `json:"gambling_fund_transfer_eligible,omitempty"`
	NameOnCard                   string     `json:"name_on_card,omitempty"`
	LastName                     string     `json:"last_name,omitempty"`
	ExpDate                      string     `json:"exp_date,omitempty"`
}
