/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

import (
	"time"
)

type BeneficialOwnerRequest struct {
	FirstName  string               `json:"first_name,omitempty"`
	MiddleName string               `json:"middle_name,omitempty"`
	LastName   string               `json:"last_name,omitempty"`
	Title      string               `json:"title,omitempty"`
	Home       *AddressRequestModel `json:"home,omitempty"`
	Ssn        string               `json:"ssn,omitempty"`
	Dob        *time.Time           `json:"dob,omitempty"`
	Phone      string               `json:"phone,omitempty"`
}
