/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type CardRequest struct {
	CardProductToken          string             `json:"card_product_token"`
	Expedite                  bool               `json:"expedite,omitempty"`
	Metadata                  map[string]string  `json:"metadata,omitempty"`
	ExpirationOffset          *ExpirationOffset  `json:"expiration_offset,omitempty"`
	Token                     string             `json:"token,omitempty"`
	UserToken                 string             `json:"user_token"`
	Fulfillment               *Fulfillment       `json:"fulfillment,omitempty"`
	ReissuePanFromCardToken   string             `json:"reissue_pan_from_card_token,omitempty"`
	TranslatePinFromCardToken string             `json:"translate_pin_from_card_token,omitempty"`
	ActivationActions         *ActivationActions `json:"activation_actions,omitempty"`
	BulkIssuanceToken         string             `json:"bulk_issuance_token,omitempty"`
}
