/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type ChargebackTransitionRequest struct {
	Token           string `json:"token,omitempty"`
	State           string `json:"state"`
	ChargebackToken string `json:"chargeback_token"`
	Reason          string `json:"reason,omitempty"`
	// Representment or prearbitration amount; this is for transitioning to Representment or Prearbitration only
	Amount float32 `json:"amount,omitempty"`
}
