/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type InternalTransactionDataModel struct {
	Pcode               string  `json:"pcode,omitempty"`
	Amount              float32 `json:"amount,omitempty"`
	RequestAmount       float32 `json:"request_amount,omitempty"`
	AdditionalAmount    float32 `json:"additional_amount,omitempty"`
	AcquirerFee         float32 `json:"acquirer_fee,omitempty"`
	Refid               int64   `json:"refid,omitempty"`
	RefItc              string  `json:"ref_itc,omitempty"`
	Account2Id          int64   `json:"account2_id,omitempty"`
	Country             string  `json:"country,omitempty"`
	Currency            string  `json:"currency,omitempty"`
	SettlementCurrency  string  `json:"settlement_currency,omitempty"`
	PaymentChannel      string  `json:"payment_channel,omitempty"`
	Itc                 string  `json:"itc,omitempty"`
	ProcessingCode      string  `json:"processing_code,omitempty"`
	IsTrackDataPresent  bool    `json:"is_track_data_present,omitempty"`
	IsCvv2Present       bool    `json:"is_cvv2_present,omitempty"`
	IsIccPresent        bool    `json:"is_icc_present,omitempty"`
	IsPinPresent        bool    `json:"is_pin_present,omitempty"`
	PanEntryMode        string  `json:"pan_entry_mode,omitempty"`
	IsCardholderPresent bool    `json:"is_cardholder_present,omitempty"`
	IsCardPresent       bool    `json:"is_card_present,omitempty"`
	Mcc                 string  `json:"mcc,omitempty"`
	Mid                 string  `json:"mid,omitempty"`
}
