/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

import (
	"time"
)

type FeeTransferResponse struct {
	Tags string      `json:"tags,omitempty"`
	Fees []FeeDetail `json:"fees"`
	// 36 char max
	Token string `json:"token"`
	// Required if 'business_token' is null
	UserToken string `json:"user_token"`
	// Required if 'user_token' is null
	BusinessToken string `json:"business_token"`
	// yyyy-MM-ddTHH:mm:ssZ
	CreatedTime *time.Time `json:"created_time"`
}
