/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type InternalUserTransactionRequest struct {
	Token string `json:"token"`
	Card *InternalCard `json:"card"`
	DigitalWalletToken string `json:"digitalWalletToken,omitempty"`
	Transaction *Transaction `json:"transaction,omitempty"`
}
