/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type FeeModel struct {
	Token string `json:"token"`
	Memo  string `json:"memo,omitempty"`
	Tags  string `json:"tags,omitempty"`
}
