/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type EchoPingResponse struct {
	Success bool   `json:"success,omitempty"`
	Id      string `json:"id,omitempty"`
	Payload string `json:"payload,omitempty"`
}
