/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

import (
	"time"
)

type Fee struct {
	// 36 char max
	Token  string `json:"token"`
	Active bool   `json:"active"`
	// 50 char max
	Name   string  `json:"name"`
	Amount float32 `json:"amount"`
	// 255 char max
	Tags string `json:"tags,omitempty"`
	// yyyy-MM-ddTHH:mm:ssZ
	CreatedTime *time.Time `json:"created_time"`
	// yyyy-MM-ddTHH:mm:ssZ
	LastModifiedTime   *time.Time             `json:"last_modified_time"`
	CurrencyCode       string                 `json:"currency_code"`
	RealTimeAssessment *RealTimeFeeAssessment `json:"real_time_assessment,omitempty"`
}
