/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type CardHolderModel struct {
	Token                   string                       `json:"token,omitempty"`
	Active                  bool                         `json:"active,omitempty"`
	Notes                   string                       `json:"notes,omitempty"`
	IpAddress               string                       `json:"ip_address,omitempty"`
	Password                string                       `json:"password,omitempty"`
	Phone                   string                       `json:"phone,omitempty"`
	Metadata                map[string]string            `json:"metadata,omitempty"`
	AccountHolderGroupToken string                       `json:"account_holder_group_token,omitempty"`
	Identifications         []IdentificationRequestModel `json:"identifications,omitempty"`
	Honorific               string                       `json:"honorific,omitempty"`
	Gender                  string                       `json:"gender,omitempty"`
	FirstName               string                       `json:"first_name,omitempty"`
	MiddleName              string                       `json:"middle_name,omitempty"`
	LastName                string                       `json:"last_name,omitempty"`
	Email                   string                       `json:"email,omitempty"`
	Address1                string                       `json:"address1,omitempty"`
	Address2                string                       `json:"address2,omitempty"`
	City                    string                       `json:"city,omitempty"`
	State                   string                       `json:"state,omitempty"`
	Country                 string                       `json:"country,omitempty"`
	BirthDate               string                       `json:"birth_date,omitempty"`
	CorporateCardHolder     bool                         `json:"corporate_card_holder,omitempty"`
	Ssn                     string                       `json:"ssn,omitempty"`
	PassportNumber          string                       `json:"passport_number,omitempty"`
	PassportExpirationDate  string                       `json:"passport_expiration_date,omitempty"`
	IdCardNumber            string                       `json:"id_card_number,omitempty"`
	IdCardExpirationDate    string                       `json:"id_card_expiration_date,omitempty"`
	Nationality             string                       `json:"nationality,omitempty"`
	Company                 string                       `json:"company,omitempty"`
	ParentToken             string                       `json:"parent_token,omitempty"`
	// Default is false
	UsesParentAccount bool   `json:"uses_parent_account,omitempty"`
	PostalCode        string `json:"postal_code,omitempty"`
}
