/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

import (
	"time"
)

type Airline struct {
	PassengerName   string     `json:"passenger_name,omitempty"`
	DepartDate      *time.Time `json:"depart_date,omitempty"`
	OriginationCity string     `json:"origination_city,omitempty"`
}
