/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type MerchantCardRequest struct {
	CardProductToken string            `json:"card_product_token"`
	Expedite         bool              `json:"expedite,omitempty"`
	Metadata         map[string]string `json:"metadata,omitempty"`
	ExpirationOffset *ExpirationOffset `json:"expiration_offset,omitempty"`
}
