/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type CardReorderRequest struct {
	// May only contain alphanumeric, hyphens, and underscore characters
	CardBatchLabel string `json:"card_batch_label,omitempty"`
}
