/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type AdvancedSimulationResponseModel struct {
	Transaction *TransactionModel      `json:"transaction,omitempty"`
	RawIso8583  map[string]interface{} `json:"raw_iso8583,omitempty"`
}
