/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type WithdrawalRequestModel struct {
	AccountType  string             `json:"account_type,omitempty"`
	CardToken    string             `json:"card_token"`
	Pin          string             `json:"pin,omitempty"`
	Mid          string             `json:"mid"`
	Amount       float32            `json:"amount"`
	CardAcceptor *CardAcceptorModel `json:"card_acceptor,omitempty"`
	Webhook      *Webhook           `json:"webhook,omitempty"`
}
