/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type AutoReloadAssociation struct {
	CardProductToken string `json:"card_product_token,omitempty"`
	UserToken        string `json:"user_token,omitempty"`
	BusinessToken    string `json:"business_token,omitempty"`
}
