/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type DirectDepositAccountTransitionRequest struct {
	AccountToken string `json:"account_token"`
	State        string `json:"state,omitempty"`
	Channel      string `json:"channel"`
	Reason       string `json:"reason,omitempty"`
	Token        string `json:"token,omitempty"`
}
