/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

import (
	"time"
)

type UserCardHolderResponse struct {
	Authentication *Authentication `json:"authentication,omitempty"`
	Token          string          `json:"token,omitempty"`
	// Default is true
	Active      bool   `json:"active,omitempty"`
	Honorific   string `json:"honorific,omitempty"`
	Gender      string `json:"gender,omitempty"`
	FirstName   string `json:"first_name,omitempty"`
	MiddleName  string `json:"middle_name,omitempty"`
	LastName    string `json:"last_name,omitempty"`
	Email       string `json:"email,omitempty"`
	Address1    string `json:"address1,omitempty"`
	Address2    string `json:"address2,omitempty"`
	City        string `json:"city,omitempty"`
	State       string `json:"state,omitempty"`
	Zip         string `json:"zip,omitempty"`
	PostalCode  string `json:"postal_code,omitempty"`
	Country     string `json:"country,omitempty"`
	Notes       string `json:"notes,omitempty"`
	Phone       string `json:"phone,omitempty"`
	ParentToken string `json:"parent_token,omitempty"`
	// Default is false
	UsesParentAccount   bool   `json:"uses_parent_account,omitempty"`
	Ssn                 string `json:"ssn,omitempty"`
	CorporateCardHolder bool   `json:"corporate_card_holder,omitempty"`
	PassportNumber      string `json:"passport_number,omitempty"`
	IdCardNumber        string `json:"id_card_number,omitempty"`
	Nationality         string `json:"nationality,omitempty"`
	Company             string `json:"company,omitempty"`
	IpAddress           string `json:"ip_address,omitempty"`
	Password            string `json:"password,omitempty"`
	// yyyy-MM-ddTHH:mm:ssZ
	CreatedTime *time.Time `json:"created_time"`
	// yyyy-MM-ddTHH:mm:ssZ
	LastModifiedTime        *time.Time                    `json:"last_modified_time"`
	BusinessToken           string                        `json:"business_token,omitempty"`
	Metadata                map[string]string             `json:"metadata,omitempty"`
	AccountHolderGroupToken string                        `json:"account_holder_group_token,omitempty"`
	Status                  string                        `json:"status,omitempty"`
	Identifications         []IdentificationResponseModel `json:"identifications,omitempty"`
	DepositAccount          *DepositAccount               `json:"deposit_account,omitempty"`
	BirthDate               string                        `json:"birth_date,omitempty"`
	PassportExpirationDate  string                        `json:"passport_expiration_date,omitempty"`
	IdCardExpirationDate    string                        `json:"id_card_expiration_date,omitempty"`
}
