/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type CardValidationRequest struct {
	Hash           string                        `json:"hash"`
	ExpirationDate string                        `json:"expiration_date,omitempty"`
	Config         map[string]string             `json:"config,omitempty"`
	DigitalWallet  *InternalDigitalWalletToken   `json:"digital_wallet,omitempty"`
	Transaction    *InternalTransactionDataModel `json:"transaction,omitempty"`
}
