/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type NetworkFeeModel struct {
	Type_  string  `json:"type,omitempty"`
	Amount float32 `json:"amount,omitempty"`
	// C = credit; D = debit
	CreditDebit string `json:"credit_debit,omitempty"`
}
