/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

import (
	"time"
)

type BeneficialOwnerResponse struct {
	FirstName  string                `json:"first_name,omitempty"`
	MiddleName string                `json:"middle_name,omitempty"`
	LastName   string                `json:"last_name,omitempty"`
	Title      string                `json:"title,omitempty"`
	Home       *AddressResponseModel `json:"home,omitempty"`
	Getdob     *time.Time            `json:"getdob,omitempty"`
	Phone      string                `json:"phone,omitempty"`
}
