/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type MsaUnloadRequestModel struct {
	Token              string  `json:"token,omitempty"`
	OriginalOrderToken string  `json:"original_order_token"`
	Amount             float32 `json:"amount"`
	Tags               string  `json:"tags,omitempty"`
	Memo               string  `json:"memo,omitempty"`
}
