/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type AdvancedAuthPoi struct {
	Other         *AdvancedAuthOtherPoi `json:"other,omitempty"`
	Ecommerce     bool                  `json:"ecommerce,omitempty"`
	Atm           bool                  `json:"atm,omitempty"`
	Moto          bool                  `json:"moto,omitempty"`
	MotoIndicator string                `json:"moto_indicator,omitempty"`
}
