/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type InternalTransactionMessage struct {
	ProcessingStartTimeMillis int64                             `json:"processing_start_time_millis,omitempty"`
	AuthorizationTranlog      *InternalAuthorizationTransaction `json:"authorization_tranlog"`
	FundingTranlog            *FundingTranlog                   `json:"funding_tranlog,omitempty"`
	VelocityCaches            []VelocityCache                   `json:"velocity_caches,omitempty"`
	Context                   map[string]interface{}            `json:"context,omitempty"`
	CreditDebitIndicator      string                            `json:"credit_debit_indicator,omitempty"`
}
