/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

import (
	"time"
)

type Gatewaylog struct {
	Id                   int64            `json:"id,omitempty"`
	TraceNumber          int64            `json:"traceNumber,omitempty"`
	PaymentTypeCode      string           `json:"paymentTypeCode,omitempty"`
	AchTransactionType   string           `json:"achTransactionType,omitempty"`
	Memo                 string           `json:"memo,omitempty"`
	GatewayVersion       string           `json:"gatewayVersion,omitempty"`
	GatewayResponse      *GatewayResponse `json:"gatewayResponse,omitempty"`
	TimedOut             bool             `json:"timedOut,omitempty"`
	DealId               int64            `json:"deal_Id,omitempty"`
	OrderId              string           `json:"order_Id,omitempty"`
	RequestMethod        string           `json:"request_method,omitempty"`
	ResponseCode         string           `json:"response_code,omitempty"`
	ResponseSubcode      string           `json:"response_subcode,omitempty"`
	ResponseReasoncode   string           `json:"response_reasoncode,omitempty"`
	ResponseMessage      string           `json:"response_message,omitempty"`
	Status               string           `json:"status,omitempty"`
	FraudAvs             string           `json:"fraud_avs,omitempty"`
	FraudAuth            string           `json:"fraud_auth,omitempty"`
	FraudCvv             string           `json:"fraud_cvv,omitempty"`
	GatewayTransactionId string           `json:"gateway_transactionId,omitempty"`
	OriginalGateway      *Gatewaylog      `json:"original_gateway,omitempty"`
	Amount               float32          `json:"amount,omitempty"`
	Duplicate            string           `json:"duplicate,omitempty"`
	PostDate             *time.Time       `json:"post_date,omitempty"`
	ResponseTime         *time.Time       `json:"response_time,omitempty"`
	ApiDuration          int64            `json:"api_duration,omitempty"`
	GatewayDuration      int64            `json:"gateway_duration,omitempty"`
	AchStatus            string           `json:"ach_status,omitempty"`
	Created              *time.Time       `json:"created,omitempty"`
	Modified             *time.Time       `json:"modified,omitempty"`
}
