/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type CardValidationResponse struct {
	Card     *InternalCard `json:"card,omitempty"`
	Response *Response     `json:"response,omitempty"`
}
