/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type VelocityControlCheckRequest struct {
	CardProduct *InternalCardProduct          `json:"card_product"`
	Transaction *InternalTransactionDataModel `json:"transaction"`
	CardHolder  *InternalUser                 `json:"card_holder"`
	Card        *InternalCard                 `json:"card,omitempty"`
	Context     map[string]string             `json:"context,omitempty"`
	WriteCache  bool                          `json:"write_cache,omitempty"`
	Debug       bool                          `json:"debug,omitempty"`
}
