/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

import (
	"time"
)

type UserStipBalanceRequest struct {
	UserToken       string     `json:"user_token"`
	IsoCurrencyCode string     `json:"iso_currency_code"`
	EffectiveTime   *time.Time `json:"effective_time,omitempty"`
	CachedBalance   float32    `json:"cached_balance"`
}
