/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type DigitalWalletTokenMetadata struct {
	IssuerProductConfigId                    string `json:"issuer_product_config_id,omitempty"`
	CardproductPreferredNotificationLanguage string `json:"cardproduct_preferred_notification_language,omitempty"`
}
