/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type AuthUserRequest struct {
	Password string `json:"password"`
	Active   bool   `json:"active,omitempty"`
	// An array of roles
	Roles    []string `json:"roles"`
	Username string   `json:"username"`
	Token    string   `json:"token,omitempty"`
}
