/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

import (
	"time"
)

type ProgramReserveTransactionResponse struct {
	// yyyy-MM-ddTHH:mm:ssZ
	CreatedTime *time.Time `json:"created_time"`
	// yyyy-MM-ddTHH:mm:ssZ
	LastModifiedTime *time.Time `json:"last_modified_time"`
	Token            string     `json:"token,omitempty"`
	Amount           float32    `json:"amount,omitempty"`
	CurrencyCode     string     `json:"currency_code,omitempty"`
	Memo             string     `json:"memo,omitempty"`
	Tags             string     `json:"tags,omitempty"`
	TransactionToken string     `json:"transaction_token,omitempty"`
	Type_            string     `json:"type,omitempty"`
	State            string     `json:"state,omitempty"`
}
