/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type ClearingAndSettlement struct {
	// Default value of GPA does not apply when JIT funding is enabled
	OverdraftDestination string `json:"overdraft_destination,omitempty"`
}
