/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

import (
	"time"
)

type CardholderNoteResponseModel struct {
	Token             string     `json:"token,omitempty"`
	Description       string     `json:"description"`
	CreatedBy         string     `json:"created_by"`
	CreatedByUserRole string     `json:"created_by_user_role,omitempty"`
	Private           bool       `json:"private,omitempty"`
	CreatedTime       *time.Time `json:"created_time,omitempty"`
	LastModifiedTime  *time.Time `json:"last_modified_time,omitempty"`
}
