/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type InternalAccount struct {
	Id                int64  `json:"id"`
	Code              string `json:"code"`
	Subclass          string `json:"subclass"`
	FinalAccount      bool   `json:"final_account,omitempty"`
	CardholderAccount bool   `json:"cardholder_account,omitempty"`
}
