/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

import (
	"time"
)

type InternalCard struct {
	Hash           string               `json:"hash,omitempty"`
	Kid            string               `json:"kid,omitempty"`
	SecureData     string               `json:"secureData,omitempty"`
	ServiceCode    string               `json:"serviceCode,omitempty"`
	Id             int64                `json:"id"`
	Token          string               `json:"token"`
	User           *InternalUser        `json:"user"`
	CardProduct    *InternalCardProduct `json:"card_product"`
	LastFour       string               `json:"last_four"`
	ExpirationTime *time.Time           `json:"expiration_time,omitempty"`
	State          string               `json:"state,omitempty"`
	Metadata       map[string]string    `json:"metadata,omitempty"`
	CardPinBlock   string               `json:"card_pin_block,omitempty"`
}
