/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type KycRequest struct {
	Notes string `json:"notes,omitempty"`
	Token string `json:"token,omitempty"`
	// Required if 'business_token' is null
	UserToken string `json:"user_token,omitempty"`
	// Required if 'user_token' is null
	BusinessToken  string `json:"business_token,omitempty"`
	ManualOverride bool   `json:"manual_override,omitempty"`
	ReferenceId    string `json:"reference_id,omitempty"`
}
