/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type UserValidationResponse struct {
	// yyyy-MM-dd
	BirthDate bool `json:"birth_date"`
	// 10 char max, phone number
	Phone bool `json:"phone"`
	// Last four digits of SSN
	Ssn bool `json:"ssn"`
	// Six-char random name postfix
	RandomNameLine1Postfix bool `json:"random_name_line1_postfix"`
}
