/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

import (
	"time"
)

type CommandoModeTransitionResponse struct {
	Type_             string                        `json:"type,omitempty"`
	Token             string                        `json:"token,omitempty"`
	CommandoModeToken string                        `json:"commando_mode_token,omitempty"`
	Transition        *CommandoModeNestedTransition `json:"transition,omitempty"`
	// yyyy-MM-ddTHH:mm:ssZ
	CreatedTime *time.Time `json:"created_time"`
	Name        string     `json:"name,omitempty"`
}
