/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type InternalAuthControlRequest struct {
	Card              *InternalCard `json:"card"`
	Cardholder        *InternalUser `json:"cardholder"`
	Mid               string        `json:"mid,omitempty"`
	Mcc               string        `json:"mcc,omitempty"`
	MccGroups         []string      `json:"mcc_groups,omitempty"`
	ControlsIndicator string        `json:"controls_indicator"`
}
