/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type RealTimeStandinCriteria struct {
	Enabled                  bool `json:"enabled,omitempty"`
	IncludeConnectionErrors  bool `json:"include_connection_errors,omitempty"`
	IncludeResponseTimeouts  bool `json:"include_response_timeouts,omitempty"`
	IncludeApplicationErrors bool `json:"include_application_errors,omitempty"`
}
