/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

import (
	"time"
)

type OfferOrderResponse struct {
	// yyyy-MM-ddTHH:mm:ssZ
	CreatedTime *time.Time `json:"created_time"`
	// yyyy-MM-ddTHH:mm:ssZ
	LastModifiedTime        *time.Time                    `json:"last_modified_time"`
	UserToken               string                        `json:"user_token,omitempty"`
	BusinessToken           string                        `json:"business_token,omitempty"`
	Token                   string                        `json:"token"`
	OrderBalances           *OfferOrderBalances           `json:"order_balances"`
	OrderAggregatedBalances *OfferOrderAggregatedBalances `json:"order_aggregated_balances"`
	Funding                 *Funding                      `json:"funding,omitempty"`
	Offer                   *OfferModel                   `json:"offer,omitempty"`
	// yyyy-MM-ddThh:mm:ssZ
	LastTransactionDate *time.Time `json:"last_transaction_date"`
}
