/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type InternalCardProduct struct {
	Token             string            `json:"token,omitempty"`
	Id                int64             `json:"id,omitempty"`
	CardProductConfig map[string]string `json:"card_product_config,omitempty"`
}
