/*
 * Marqeta Core API
 *
 * Simplified management of your payment programs
 *
 * API version: 3.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package marqeta

type BusinessIncorporationResponse struct {
	IsPublic               bool                  `json:"is_public,omitempty"`
	StockSymbol            string                `json:"stock_symbol,omitempty"`
	StateOfIncorporation   string                `json:"state_of_incorporation,omitempty"`
	NameRegisteredUnder    string                `json:"name_registered_under,omitempty"`
	AddressRegisteredUnder *AddressResponseModel `json:"address_registered_under,omitempty"`
	IncorporationType      string                `json:"incorporation_type,omitempty"`
}
